### ISSUE TITLE
Problems with limits.conf

### ISSUE THREAD

**Issue by fri-it2** [perfsonar/ansible-role-perfsonar-testpoint#17]
Hello!
I installed perfSONAR testpoints with  ansible-role-perfsonar-testpoint. 
No measuments to testpoints with new ```http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.9-1.noarch.rpm```  could be done(tests works just to to testpoints with ```old http://software.internet2.edu/rpms/el7/x86_64/main/RPMS/perfSONAR-repo-0.8.*.noarch.rpm```)
It should be repaired **limits.conf**.  perfsonar subnet should be add to classifiers: friendlies
Example limits.conf:

```
"name": "perfsonar",
            "description": "Our perfsonar network",
            "type": "ip-cidr-list",
            "data": {
                "cidrs": [ "2001:100:7000:899::/56","192.168.41.144/24" ]
            }
        },


  "classifiers": [
    {
        "name": "friendlies",
        "description": "Identifiers we find friendly",
        "identifiers": [ "local-interfaces","r-and-e", "r-and-e1","r-and-e2","r-and-e3", "perfsonar"]
    },

```

**Comment by igarny** [comment]
Hello S56ZSA,

Could you please clarify more your issue?
"No measurements with new"? what? Please do not expect us to make wild guesses.
old? is this an old install or an old run

The limits.conf example is not the one provided with perfSONAR initial deployment.
I would strongly recommend to use the mailling list: perfsonar-user@internet2.edu for unclarified issues, like in your case. 
Community can also help!

**Comment by laeti-tia** [comment]
Issue not relevant to this Ansible role.
