### ISSUE TITLE
ansible error: Unexpected failure in finding the lookup

### ISSUE THREAD

**Issue by vvidic** [perfsonar/ansible-role-perfsonar-testpoint#5]
I'm getting this error now when installing a new host:

```
TASK [ansible-role-perfsonar-testpoint : Delete psconfig remotes] **************
skipping: [pstest2.geant.carnet.hr] => (item={u'url': u'http://mca-nightly.grnoc.iu.edu/pub/config/testbed-nightly?format=psconfig', u'state': u'present'})
ERROR! Unexpected failure in finding the lookup named '{{ perfsonar_archive_auth_interfaces | product(perfsonar_archive_hosts) | list }}' in the available lookup plugins
```

**Comment by epcjr** [comment]
It may be failing on the "product" filter.  What version of Ansible are you
running?

Thanks,

-Ed

**Comment by vvidic** [comment]
On Fri, Feb 01, 2019 at 04:16:05AM -0800, epcjr wrote:
> It may be failing on the "product" filter.  What version of Ansible are you
> running?

This is again ansible 2.2.1.0.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by epcjr** [comment]
That's a really old version of Ansible.  Can you upgrade to the current
version?

Thanks,

-Ed

**Comment by vvidic** [comment]
On Fri, Feb 01, 2019 at 01:10:04PM +0000, epcjr wrote:
> That's a really old version of Ansible.  Can you upgrade to the current
> version?

Not really, but I can try something a bit newer.

-- 
Valentin Vidic
Computer Systems Engineer - Expert
Department of Computer Infrastructure and Services
Croatian Academic and Research Network - CARNET
Josipa Marohnica 5, HR-10000 Zagreb, Croatia
tel: +385 1 6661 714, fax. +385 1 6661 635
gsm: +385 91 2480 919
www.CARNet.hr

**Comment by laeti-tia** [comment]
Hi Valentin,

> Le 1 févr. 2019 à 17:09, Valentin Vidić <notifications@github.com> a écrit :
> 
> On Fri, Feb 01, 2019 at 01:10:04PM +0000, epcjr wrote:
> > That's a really old version of Ansible. Can you upgrade to the current
> > version?
> 
> Not really, but I can try something a bit newer.

We decided that we would support Ansible that is in Debian backports. Can you try that version?

Thanks,

-- Antoine --

**Comment by vvidic** [comment]
Yes, it seems better with ansible 2.6 now. I will close the issue.
