### ISSUE TITLE
Lookup Service Registration Daemon configuration management

### ISSUE THREAD

**Issue by igarny** [perfsonar/ansible-role-perfsonar-testpoint#6]
It would be nice to have the LSRD configuration managed by Ansible for the hosts by assigning template variables for each param.

**Comment by epcjr** [comment]
Ivan, I will reach out to you in a week or two to collaborate on this task.  I will help with the automation, would like a little guidance on the config file itself.

Thanks!

**Comment by vvidic** [comment]
Is someone working on this already?

**Comment by vvidic** [comment]
Please check the proposed PR #11

**Comment by vvidic** [comment]
PR #11 merged so closing here too.
