### ISSUE TITLE
problem empty param for psconfig remotes management

### ISSUE THREAD

**Issue by igarny** [perfsonar/ansible-role-perfsonar-testpoint#9]
Essentially the problem is: 
Ansible script replaces the parameter position with empty string..... but psconfig is unhappy
psconfig asks if a parameter is supplied, it should not be empty or incorrect (my guess as any other command)

reference to details: https://github.com/perfsonar/ansible-role-perfsonar-testpoint/commit/b1358bc949da19d936497be597cd460817ea7338#r32856153

**Comment by vvidic** [comment]
Please test PR #10 for this again.

**Comment by vvidic** [comment]
This should work now with `configure_archives: True`, so closing here.
